---
deployment:
  tasks:
    - export DEPLOYPATH=/home/r6pephbnqdt7/public_html/
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    /bin/cp index.php $DEPLOYPATH